from __future__ import annotations

import json
from pathlib import Path


def codex_baseline() -> str:
    return """# Generated by FoundLab AI Ops. Review before installing.
model_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "cached"

[shell_environment_policy]
ignore_default_excludes = false
"""


def gemini_baseline() -> dict:
    return {
        "general": {
            "defaultApprovalMode": "default",
        },
        "security": {
            "environmentVariableRedaction": {
                "enabled": True,
            },
        },
        "telemetry": {
            "enabled": True,
            "target": "gcp",
            "useCliAuth": True,
            # Prompt bodies are not required for compute/usage governance.
            "logPrompts": False,
        },
        "hooks": {
            "BeforeTool": [
                {
                    "matcher": "write_file|replace|run_shell_command|mcp_.*",
                    "sequential": True,
                    "hooks": [
                        {
                            "name": "foundlab-policy-guard",
                            "type": "command",
                            "command": "flops hook gemini-before-tool",
                            "timeout": 5000,
                            "description": "FoundLab deterministic policy gate",
                        }
                    ],
                }
            ]
        },
    }


def write_codex(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(codex_baseline(), encoding="utf-8")
    return path


def write_gemini(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(gemini_baseline(), indent=2) + "\n", encoding="utf-8")
    return path
